# Generated by Django 2.0.7 on 2018-07-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passrequest',
            name='account',
        ),
        migrations.RemoveField(
            model_name='passrequest',
            name='registered',
        ),
    ]
