version: '2'
services:
  base:
    restart: unless-stopped
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data/

  upgrade:
    restart: unless-stopped
    extends: base
    command: bash -c "mkdir -p data/db && python manage.py migrate"

  web:
    restart: unless-stopped
    extends: base
    command: gunicorn eos_faucet.wsgi -b 0.0.0.0:8000 --workers=4 --timeout=120 --log-level=debug

    ports:
      - '8000:8000'
