# Generated by Django 2.0.7 on 2018-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
